language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - "pip freeze"
  - "[ \"$TRAVIS_PYTHON_VERSION\" != '2.6' ] || pip install ." # travis python 2.6 doesn't seem to install package
  - "[ \"$TRAVIS_PYTHON_VERSION\" != '2.6' ] || pip install --use-mirrors unittest2"
script:
  - |
    if [ "$TRAVIS_PYTHON_VERSION" != '2.6' ]; then
      python setup.py test
    else
      unit2 discover
    fi
